New addon temps
Windower/Lua pull request #1522
Opened 2017-04-19 15:15 UTC by Snapsmojo

This addon accepts commands to buy temporary items from escha npcs.

2017-04-19 15:26 UTC, z16 requested changes
Added some minor suggestions and some required changes to the copyright notice. It would also be nice to include a ReadMe.md file, which will be displayed if the user clicks on the "About" link on the addons tab.

2017-04-19 15:26 UTC, z16 commented on addons/temps/temps.lua
> +* Neither the name of timestamp nor the
Use `temps` here instead of `timestamp`.

2017-04-19 15:26 UTC, z16 commented on addons/temps/temps.lua
> +    local args = {select(2, ...)}
You only use `args` to unpack it again later, so you could save yourself the effort by just doing `handlers[cmd](select(..., 2))` later (or, if you took my suggestion above, `handlers[cmd](...)`).

2017-04-19 15:26 UTC, z16 commented on addons/temps/temps.lua
> +    local cmd  = (...) and (...):lower()
To save some effort here, you can change the function signature:
```lua
local function handle_command(cmd, ...)
```

That will parse the first argument for you.

You can also default to 'help' if it's not passed, which would be more user-friendly and save you the last case below:
```lua
    cmd = cmd and cmd:lower() or 'help'
```

2017-04-19 15:28 UTC, z16 commented on addons/temps/temps.lua
> +* Neither the name of timestamp nor the
For some reason it removed my other comment... below it says "Giuliano Riccio", replace that with your name (either real or alias as above, preferably the same name as in the opening line).

2017-04-19 16:03 UTC, joshk6656 commented
This is interesting, I recently researched this and I was pretty sure the NPC in Reisenjima did not work like other menu NPC's. Did you do any testing in that area? I'm not doubting but kind of baffled why I couldn't find this info. Mojo do you ever use IRC anymore, I have an unrelated question.

2017-04-19 16:30 UTC, Snapsmojo commented
I pushed a few commits addressing the feedback here.  I am rarely on IRC but you can usually message me on ffxiah or bg.

2017-04-20 07:00 UTC, merged

2017-04-20 07:01 UTC, z16 commented
Ah crap.... now I pulled prematurely. One thing is still missing: An entry into the `addons.xml` file. Please provide that in a new pull request, otherwise the addon won't show up in the Windower launcher, so people won't be able to download it.