Fixing up packets\fields.lua 0x03c
Windower/Lua pull request #1539
Opened 2017-05-10 02:17 UTC by SammehFFXI

Adding 'Craft Skill' and 'Craft Rank' unsigned shorts to fields.lua to
correctly track that incoming 0x03c packet.

2017-05-10 02:46 UTC, cairface commented on addons/libs/packets/fields.lua
> +	{ctype='unsigned short',    label='Craft Rank'},                            -- Correlates to Rank able to purchase product from GuildNPC
Whatever editor you're using, find out how to change tabs to spaces, make 1 tab = 4 spaces. :)

2017-05-10 06:24 UTC, z16 requested changes

2017-05-10 06:24 UTC, z16 commented on addons/libs/packets/fields.lua
> +	{ctype='unsigned short',    label='Craft Skill'},                           -- Zero on normal shops, has values that correlate to res\skills.
You're using tabs. Please switch to 4 spaces (in this and all of your pull requests).

2017-05-11 00:00 UTC, SammehFFXI commented
Changed to spaces as requested

2017-05-11 01:13 UTC, merged